name: Build and Push Docker Images to ECR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build, tag, and push frontend image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          GIT_SHA: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:frontend-$GIT_SHA -t $ECR_REGISTRY/$ECR_REPOSITORY:frontend-latest ./view
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:frontend-$GIT_SHA
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:frontend
          
      - name: Build, tag, and push backend image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          GIT_SHA: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:backend-$GIT_SHA -t $ECR_REGISTRY/$ECR_REPOSITORY:backend-latest ./api
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:backend-$GIT_SHA
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:backend